export * from './MainPage'
export * from './PaymentPage'
export * from './DeliveryPage'
export * from './NewProductPage'
export * from './AboutPage'
export * from './NotFound'
export * from './ProductTypesPage'
export * from './ProductListPage'